name: "Tanzu Run Shell Script Setup Action"
description: "Execute a shell script where kubectl and/or tanzu CLI commands may be invoked one or more times"
inputs:
  enable-tanzu-cli:
    description: "Whether or not to install the tanzu CLI and configure plugins"
    required: false
    default: "false"
  script-contents:
    description: "The base64 encoded contents of a shell script"
    required: true
  script-arguments:
    description: "A space separated set of arguments that the script will consume"
    required: true
  kubeconfig-contents:
    description: "The base64 encoded contents of a .kube/config file that already has the current Kubernetes cluster context set"
    required: false
  google-project-id:
    description: "The Google project identifier"
    required: true
  google-service-account-key:
    description: "The base64 encoded content of the service account JSON file"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.script-contents }}"
    - "${{ inputs.script-arguments }}"
    - "${{ inputs.kubeconfig-contents }}"
  env:
    GOOGLE_PROJECT_ID: ${{ inputs.google-project-id }}
    GOOGLE_SERVICE_ACCOUNT_KEY: ${{ inputs.google-service-account-key }}
    TANZU_CLI_ENABLED: ${{ inputs.enable-tanzu-cli }}
